name: nextjs
version: "1.0"
description: Next.js application
before: [nodejs]
image: "{{image}}"
port: 3000
build:
  - "{{pm_install}}"
  - "{{pm_run}} build"
include:
  - package.json
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - bun.lockb
  - node_modules/
  - .next/
  - public/
  - "next.config.*"
start: "{{pm_start}}"
health:
  path: /
  interval: 10
  timeout: 5
  retries: 3
